### ISSUE TITLE
游戏项目如何增加ipad mini6的分辨率~

### ISSUE THREAD

**Issue by Vrwkey** [halx99/x-studio365#905]
x-studio
 的游戏项目，如何增加ipad mini6的分辨率~

**Comment by halx99** [comment]
【菜单】【打开】【打开软件配置文件】在`designsize-list`节点下添加相应分辨率，保存，之后重启软件即可:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/6977319/162554743-c8a1b915-5b84-48bb-ba48-ba0a370f6b70.png">
